### ISSUE TITLE
No album art

### ISSUE THREAD

**Issue by eson57** [equeim/unplayer#19]
Album art is gone from v1.0.0. Don't know what happened but worked fine in previous version.

**Comment by ghost** [comment]
Same problem here. Why was tracker abandoned in favour of a scanning mechanism specific to Unplayer?

**Comment by equeim** [comment]
Tracker dependency was removed because the libraries which Unplayer had to use could become incompatible or even removed in future versions of Sailfish OS. Shipping them in the package would be too complicated.
Currently Unplayer can only find covers as separate files in the same directory as tracks (they should be named as albumart/cover/folder/front with jpeg, jpg, or png extensions). Unfortunately it is broken in 1.0.0. I will fix it quickly.
Also I plan to add support of extracting covers that are embedded in music files (it would probably be in 1.1).

**Comment by ghost** [comment]
I see, thanks for the explanation.

**Comment by eson57** [comment]
Well, since searching and collecting 300+ cover images is out of question, I'll just have to wait for v1.1 then. 
Thanks for info.

**Comment by equeim** [comment]
BTW, what should have higher priority? Cover from file or from its directory?

**Comment by eson57** [comment]
If you ask me, it's cover from music file. I have all my covers embedded. I think most people do.

**Comment by equeim** [comment]
Hmm, I should probably make it configurable.

**Comment by eson57** [comment]
That would be great.
