### ISSUE TITLE
Feature request: AVRCP control

### ISSUE THREAD

**Issue by mase76** [equeim/unplayer#42]
Hi!
It would be nice, if the player could be controlled with the bluetooth headset buttons via AVRCP. Also automated pausing when disconnected.

**Comment by equeim** [comment]
Version from OpenRepos should support headset buttons, although I can't test it since I don't have a headset with buttons. Also I don't know if it would work with bluetooth headset, but I would assume that it should, since it uses generic Sailfish.Media API (it's private and is not allowed to use in Jolla Store apps). Pausing when headset is disconnected works with regular wired headset and is done automatically inside QtMultimedia framework. If it doesn't work for bluetooth headsets, I have no idea how to fix it.

**Comment by mase76** [comment]
Yes, it works when the mpris-proxy is running.
