### ISSUE TITLE
Not Playing

### ISSUE THREAD

**Issue by benaryorg** [equeim/unplayer#8]
My old Jolla broke so I got a new one and Unplayer just doesn't work on the new one.
The old one was just working fine, on the new one when I press play it immediately stops and I don't know why.

I tried:
- reinstalling
- installing an old version
- using with or without headphones
- updating every package on my system
- reinstalling every package on my system

SFOS version: latest (Saimaa)

**Comment by benaryorg** [comment]
Also, the Jolla player is working fine.

**Comment by benaryorg** [comment]
I finally tracked down the error to this console output:

``` text
** Message: don't know how to handle audio/x-flac
```

and for mp3 files:

``` text
** Message: don't know how to handle application/x-id3
```

**Comment by benaryorg** [comment]
I fixed it by running

``` bash
rm -rf ~/.config/tracker ~/.local/share/tracker
```

**Comment by Kabouik** [comment]
Unfortunately, it has not solved the exact same problem for me. I tried _tracker-control --hard-reset_ too, with no success.

**Comment by benaryorg** [comment]
Maybe this should be reopened then?

**Comment by Kabouik** [comment]
Maybe, but in fact, there is another similar issue still open [here](https://github.com/equeim/unplayer/issues/11). Both threads seem to be about the same issue, but I started with this one because I saw that you managed to fix it with the above command.

Is @equeim is still maintaining Unplayer? Maybe he doesn't follow Github anymore (his last contributions were 2 months ago) and doesn't know about this issue. There are similar reports in Openrepos comments too.

**Comment by benaryorg** [comment]
Regarding @equeim: their last activity on GitHub was 27 days ago so maybe something has happened that either prevents them from using GitHub or they have no more interest in GitHub at all.

Regarding Unplayer: what exactly does your console output look like?
Is it similar to mine or similar to the output in #11?
